AimsSoft/urls.py
from django.contrib import admin
from django.urls import path, include

from inventory import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('api/', include('inventory.api.urls')),
    path('inventory/', include('inventory.urls')),
]

inventory/api/urls.py
from django.urls import path

from inventory.api.views import CustomerView, index, ExpenseView, \
    CustomerExpense, RecentCustomerView

app_name = 'rest'
urlpatterns = [
    path('customers/', CustomerView.as_view()),
    path('customers/<int:pk>/', CustomerView.as_view()),
    path('customers/<int:pk>/expense', CustomerExpense.as_view()),
    path('customers/<slug:customer_id>/', CustomerView.as_view()),
    path('customers/<int:customer>/expenses/', ExpenseView.as_view()),
    path('customers/<slug:customer_id>/expenses/', ExpenseView.as_view()),
    path('customers/<int:customer>/expenses/<int:recv>/', ExpenseView.as_view()),
    path('recent/customers', RecentCustomerView.as_view()),
    path('', index)
]

inventory/urls.py
from django.urls import path

from inventory import views

app_name = 'inventory'

urlpatterns = [
    path('customers/', views.customers, name='customers'),
    path('customer/new/', views.new_customer, name='new_customer'),
    path('customer/<int:cust_id>/', views.customer_details, name='cust_detail'),
    path('customer/<int:cust_id>/payment/', views.payment, name='payment'),
    path('customer/<int:cust_id>/purchase/', views.purchase, name='purchase'),
    path('customer/<int:cust_id>/payment/<int:payment_id>/edit', views.edit_payment, name='edit_payment'),
    path('customer/<int:cust_id>/purchase/<int:purchase_id>/edit', views.edit_purchase, name='edit_purchase'),
]

inventory/models.py
from django.utils import timezone
from django.db import models

PAYMENT_METHODS = [('card', 'Card'), ('online', 'Online'), ('cash', 'Cash')]
PRIVILEGES = [('admin', 'Admin'), ('employee', 'Employee'), ('guest', 'Guest')]


class User(models.Model):
    user_id = models.CharField(max_length=50, blank=True)
    password = models.CharField(max_length=50, blank=True)
    date_added = models.DateTimeField(default=timezone.now, blank=True)
    role = models.CharField(choices=PRIVILEGES, max_length=20, default='employee')

    def __str__(self):
        return str(self.user_id)


class Customer(models.Model):
    customer_id = models.CharField(max_length=25, blank=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    address = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=100, blank=True)
    email = models.CharField(max_length=100, blank=True)
    about = models.CharField(max_length=250, blank=True)
    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(default=timezone.now, blank=True)
    balance_amount = models.IntegerField(default=0)
    pending_amount = models.IntegerField(default=0)

    def __str__(self):
        return '%s(%s)' % (self.first_name, self.customer_id)


class Payment(models.Model):
    customer = models.ForeignKey(Customer, related_name='expenses', on_delete=models.PROTECT)
    expense_id = models.CharField(max_length=25)
    amount = models.IntegerField(default=0)
    payment_method = models.CharField(choices=PAYMENT_METHODS, max_length=20)
    received_by = models.ForeignKey(User, related_name='received_by', on_delete=models.PROTECT, default=1)
    payment_date = models.DateTimeField(default=timezone.now)
    is_draft = models.BooleanField(default=True)

    def __str__(self):
        return '%s(%s)' % ('RS:' + str(self.amount), self.customer)


class Purchase(models.Model):
    customer = models.ForeignKey(Customer, related_name='purchase', on_delete=models.PROTECT)
    purchase_id = models.CharField(max_length=25)
    purchase_from = models.CharField(max_length=150)
    item = models.CharField(max_length=200)
    unit_price = models.IntegerField(default=0)
    num_unit = models.IntegerField(default=0)
    total_cost = models.IntegerField(default=0)
    purchase_date = models.DateField(default=timezone.now)
    added_date = models.DateField(default=timezone.now)
    is_draft = models.BooleanField(default=True)

    def __str__(self):
        return '%s(%s)' % (self.item, self.customer)

inventory/api/views.py
from django.http import HttpResponse
from rest_framework import generics
from rest_framework import mixins

from inventory.api.serializers import CustomerSerializer, \
    CustomerDetailSerializer, ExpenseSerializer, CustomerExpenseSerializer
from inventory.models import Customer, Payment


class CustomerView(generics.GenericAPIView,
                   mixins.CreateModelMixin,
                   mixins.UpdateModelMixin,
                   mixins.DestroyModelMixin,
                   mixins.ListModelMixin,
                   mixins.RetrieveModelMixin):

    queryset = Customer.objects.all()
    serializer_class = CustomerDetailSerializer

    def get(self, request, pk=None, *args, **kwargs):
        if pk:
            return self.retrieve(request, *args, **kwargs)

        self.serializer_class = CustomerSerializer
        return self.list(request, *args, **kwargs)

    def post(self, request, pk=None, *args, **kwargs):
        if pk:
            return self.update(request, *args, **kwargs)
        request.data._mutable = True
        request.data['customer_id'] = CustomerView._get_customer_id('BUILD')
        request.data._mutable = False
        return self.create(request, *args, **kwargs)

    @staticmethod
    def _get_customer_id(construction):
        ret = 'AC'
        ret += construction[0]
        cust_list = Customer.objects.filter(customer_id__startswith=ret)
        last_customer = cust_list.order_by('id')[cust_list.count() - 1]
        next_int = int(last_customer.customer_id[3:]) + 1
        return ret + str(next_int).zfill(3)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class ExpenseView(generics.GenericAPIView,
                  mixins.ListModelMixin,
                  mixins.DestroyModelMixin,
                  mixins.CreateModelMixin):
    queryset = Payment.objects.all()
    serializer_class = ExpenseSerializer

    def get(self, request, customer=None, customer_id=None,
            recv=None, *args, **kwargs):
        # Filter data if customer ID is provided
        if customer_id:
            customer = Customer.objects.get(customer_id=customer_id)
            self.queryset = Payment.objects.filter(customer=customer.id)
        else:
            self.queryset = Payment.objects.filter(customer=customer)

        # Filter received/paid expenses
        if recv:
            if recv == 1:
                self.queryset = self.queryset.filter(received=True)
            elif recv == 2:
                self.queryset = self.queryset.filter(received=False)
            elif recv == 0:
                pass
            else:
                self.queryset = Payment.objects.none()
        return self.list(request, *args, **kwargs)

    @staticmethod
    def _get_expense_id():
        expense_num = Payment.objects.count() + 1
        return 'EXP' + str(expense_num).zfill(3)

    def post(self, request, customer, *args, **kwargs):
        request.data._mutable = True
        request.data['expense_id'] = ExpenseView._get_expense_id()
        request.data['customer'] = customer
        request.data._mutable = False
        return self.create(request, *args, **kwargs)


class CustomerExpense(generics.GenericAPIView,
                      mixins.RetrieveModelMixin):

    queryset = Customer.objects.all()
    serializer_class = CustomerExpenseSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)


class RecentCustomerView(generics.GenericAPIView,
                         mixins.ListModelMixin):
    queryset = Customer.objects.all().order_by('-date_added')[:5]
    serializer_class = CustomerSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, *kwargs)


def index(request):
    return HttpResponse('Rest framework')

inventory/views.py
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from datetime import datetime

from inventory.models import Customer, Payment, Purchase, User

MAX_PLACE_DISP_LEN = 19


class GraphData(object):
    MONTH_LIST = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

    def __init__(self):
        month = int(timezone.now().strftime('%-m')) - 1
        self.month = self._get_month_list(month)
        self.num_cust = self._get_num_cust_list()
        self.num_comp = self._get_num_comp_list()

    def _get_month_list(self, month):
        month_list = self.MONTH_LIST * 2
        month_list = month_list[month + 12 - 6:month + 12 + 1]
        month_list.reverse()
        return month_list

    def _get_num_cust_list(self):
        num_cust = []
        for month in self.month:
            num_month = self.MONTH_LIST.index(month) + 1
            num_cust.append(Customer.objects.filter(date_added__month=num_month).count())
        return num_cust

    def _get_num_comp_list(self):
        num_cust = []
        for month in self.month:
            num_month = self.MONTH_LIST.index(month) + 1
            num_cust.append(Customer.objects.filter(date_added__month=num_month).count())
        return num_cust


def index(request):
    context = {}
    recent_cust = Customer.objects.all().order_by('-date_added')[:5]
    if recent_cust.count() > 0:
        last_cust_date = recent_cust[0].date_added
        last_cust_date = last_cust_date.strftime("%b %d, %Y")
        context['last_cust_date'] = last_cust_date
        for cust in recent_cust:
            if len(cust.address) > MAX_PLACE_DISP_LEN:
                cust.address = cust.address[:17] + '...'

    recent_payments = Payment.objects.all().order_by().order_by('-payment_date')[:5]
    if recent_payments.count() > 0:
        last_pay_date = recent_payments[0].payment_date
        last_pay_date = last_pay_date.strftime("%b %d, %Y")
        context['last_pay_date'] = last_pay_date

    graph_data = GraphData()

    context.update({
        'graph_data': graph_data,
        'recent_cust': recent_cust,
        'recent_payments': recent_payments,
    })
    return HttpResponse(render(request, 'dashboard.html', context))


def customers(request):
    all_customers = Customer.objects.all()
    context = {
        'all_customers': all_customers
    }
    return HttpResponse(render(request, 'customers.html', context))


def customer_details(request, cust_id):
    customer = get_object_or_404(Customer, pk=cust_id)
    total_purchase = Purchase.objects.filter(customer_id=cust_id, is_draft=False).aggregate(Sum('total_cost'))['total_cost__sum']
    total_payment = Payment.objects.filter(customer_id=cust_id, is_draft=False).aggregate(Sum('amount'))['amount__sum']
    total_purchase = 0 if not total_purchase else total_purchase
    total_payment = 0 if not total_payment else total_payment
    context = {
        'customer': customer,
        'total_purchase': total_purchase,
        'total_payment': total_payment,
        'balance_str': 'Amount due' if total_payment < total_purchase else 'Balance',
        'total_balance': abs(total_purchase - total_payment),
    }
    return HttpResponse(render(request, 'cust_details.html', context))


def new_customer(request):
    context = {}
    if request.method == 'POST':
        customer = Customer()
        customer.customer_id = request.POST['cust-id']
        customer.first_name = request.POST['first-name']
        customer.last_name = request.POST['last-name']
        customer.address = request.POST['address']
        customer.city = request.POST['city']
        customer.country = request.POST['country']
        customer.postal_code = request.POST['postal-code']
        customer.phone = request.POST['phone']
        customer.email = request.POST['email']
        customer.about = request.POST['about']

        if customer.first_name and customer.phone and customer.address:
            customer.save()
            context = {'success_msg': 'New user added successfully'}
        else:
            context = {'error_msg': 'Please fill the mandatory fields marked <span class="text-danger">*</span>'}

    return HttpResponse(render(request, 'new_customer.html', context))


def payment(request, cust_id):
    if request.method == 'POST':
        counter = 0
        Payment.objects.filter(customer_id=cust_id, is_draft=True).delete()
        while True:
            counter_str = str(counter)
            if not request.POST.get('received-by' + counter_str):
                break
            payment_item = Payment()
            payment_item.customer = Customer.objects.get(pk=cust_id)
            aims_user = request.POST['received-by' + counter_str]
            payment_item.received_by = User.objects.get(user_id=aims_user)
            payment_item.payment_method = request.POST['method' + counter_str]
            payment_item.amount = request.POST['payment' + counter_str]
            payment_item.payment_date = request.POST['payment-date' + counter_str]

            post_date = request.POST['payment-date' + counter_str]
            payment_item.payment_date = datetime.strptime(post_date, '%d/%m/%Y').strftime('%Y-%m-%d')
            if request.POST['submit-type'] == 'submit':
                payment_item.is_draft = False
            payment_item.save()
            counter += 1

    if request.POST.get('submit-type') == 'submit':
        return customer_details(request, cust_id)

    draft = Payment.objects.filter(customer_id=cust_id, is_draft=True)
    customer = get_object_or_404(Customer, pk=cust_id)
    users = User.objects.all()
    context = {'customer': customer, 'draft': draft, 'users': users}
    if request.method == 'POST':
        context['success_msg'] = 'Data saved successfully'
    return HttpResponse(render(request, 'payment.html', context))


def purchase(request, cust_id):
    if request.method == 'POST':
        counter = 0
        Purchase.objects.filter(customer_id=cust_id, is_draft=True).delete()
        while True:
            counter_str = str(counter)
            if not request.POST.get('item-name' + counter_str):
                break
            purchase_item = Purchase()
            purchase_item.customer = Customer.objects.get(pk=cust_id)
            purchase_item.item = request.POST['item-name' + counter_str]
            purchase_item.purchase_from = request.POST['purchase-from' + counter_str]
            purchase_item.num_unit = request.POST['num-units' + counter_str]
            purchase_item.unit_price = request.POST['unit-price' + counter_str]
            purchase_item.total_cost = request.POST['total-cost' + counter_str]
            post_date = request.POST['purchase-date' + counter_str]
            purchase_item.purchase_date = datetime.strptime(post_date, '%d/%m/%Y').strftime('%Y-%m-%d')
            if request.POST['submit-type'] == 'submit':
                purchase_item.is_draft = False
            purchase_item.save()
            counter += 1

    if request.POST.get('submit-type') == 'submit':
        return customer_details(request, cust_id)

    draft = Purchase.objects.filter(customer_id=cust_id, is_draft=True)
    customer = get_object_or_404(Customer, pk=cust_id)
    context = {'customer': customer, 'draft': draft}
    if request.method == 'POST':
        context['success_msg'] = 'Data saved successfully'
    return HttpResponse(render(request, 'purchase.html', context))


def edit_payment(request, cust_id, payment_id):
    _payment = Payment.objects.get(pk=payment_id)
    _payment.is_draft = True
    _payment.save()
    draft = Payment.objects.filter(customer_id=cust_id, is_draft=True)
    customer = get_object_or_404(Customer, pk=cust_id)
    users = User.objects.all()
    context = {'customer': customer, 'draft': draft, 'users': users}
    return HttpResponse(render(request, 'payment.html', context))


def edit_purchase(request, cust_id, purchase_id):
    _purchase = Purchase.objects.get(pk=purchase_id)
    _purchase.is_draft = True
    _purchase.save()
    draft = Purchase.objects.filter(customer_id=cust_id, is_draft=True)
    customer = get_object_or_404(Customer, pk=cust_id)
    context = {'customer': customer, 'draft': draft}
    return HttpResponse(render(request, 'purchase.html', context))

inventory/templates/all_customers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Aims Customers</title>
</head>
<body>
    {% if all_customers %}
        <ul>
            {% for customer in all_customers %}
                <li><a href="{% url 'inventory:cust_details' customer.pk %}">{{ customer.customer_name }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
</body>
</html>

inventory/templates/cust_details.html
{% extends 'aims_base.html' %}
{% load mathfilters %}
{% block title %}Customers{% endblock %}
{% block customers_active %}active{% endblock %}
{% block page_head %}Customer Details{% endblock %}
{% block body %}
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary float-left">
                    <div class="col-md-8 float-left">
                        <h4 class="card-title ">{{ customer.first_name }} {{ customer.last_name }}</h4>
                        <p class="card-category">{{ customer.address }}</p>
                    </div>
                    <div class="float-right table-condensed">
                    <table>
                        <tr><td>Phone:</td><td>{{ customer.phone }}</td></tr>
                        <tr><td>Email:</td><td>{{ customer.email }}</td></tr>
                    </table>
                  </div>
                </div>
                <div class="card-body">
                  <div class="aims-sub-head">
                      <div class="h4 aims-wrap-content">Payment</div>
                      <a class="aims-wrap-content float-right my-auto" href="{% url 'inventory:payment' customer.pk %}">
                        <i class="material-icons aims-material-btn">add</i>
                      </a>
                  </div>
                  <div class="table-responsive">
                    <table class="table">
                      <thead class="text-primary">
                        <th>ID</th>
                        <th>Received By</th>
                        <th>Method</th>
                        <th>Payment Date</th>
                        <th>Amount</th>
                        <th class="aims-tbl-col-1"></th>
                      </thead>
                      <tbody>
                      {% for payment in customer.expenses.all %}
                        {% if not payment.is_draft %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ payment.received_by }}</td>
                          <td>{{ payment.payment_method }}</td>
                          <td>{{ payment.payment_date|date:"M d, Y h:i:s A" }}</td>
                          <td class="text-primary">&#8377;{{ payment.amount }}</td>
                          <td>
                            <a class="aims-wrap-content float-right my-auto" href="{% url 'inventory:edit_payment' customer.pk payment.pk %}">
                              <i class="material-icons aims-material-btn">edit</i>
                            </a>
                          </td>
                        </tr>
                        {% endif %}
                      {% endfor %}
                      </tbody>
                      <tfoot class="text-primary">
                        <tr>
                          <td class="text-right aims-no-border aims-primary-text" colspan="4">Total</td>
                          <td class="aims-no-border aims-primary-text">&#8377;{{ total_payment }}</td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                  <div class="aims-sub-head">
                    <div class="h4 aims-wrap-content">Purchase</div>
                    <a class="aims-wrap-content float-right my-auto" href="{% url 'inventory:purchase' customer.pk %}">
                      <i class="material-icons aims-material-btn">add</i>
                    </a>
                  </div>
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>ID</th>
                        <th>Purchase from</th>
                        <th>Item</th>
                        <th>Unit price</th>
                        <th class="aims-tbl-col-1">No. Units</th>
                        <th>Date</th>
                        <th>Total Amount</th>
                        <th class="aims-tbl-col-1"></th>
                      </thead>
                      <tbody>
                      {% for purchase in customer.purchase.all %}
                        {% if not purchase.is_draft %}
                        <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>{{ purchase.purchase_from }}</td>
                          <td>{{ purchase.item }}</td>
                          <td>{{ purchase.unit_price }}</td>
                          <td>{{ purchase.num_unit }}</td>
                          <td>{{ purchase.purchase_date|date:"d/m/Y" }}</td>
                          <td class="text-primary"> &#8377;{{ purchase.total_cost }}</td>
                          <td>
                            <a class="aims-wrap-content float-right my-auto" href="{% url 'inventory:edit_purchase' customer.pk purchase.pk %}">
                              <i class="material-icons aims-material-btn">edit</i>
                            </a>
                          </td>
                        </tr>
                        {% endif %}
                      {% endfor %}
                      </tbody>
                      <tfoot class="text-primary">
                        <tr>
                          <td class="text-right aims-no-border aims-primary-text" colspan="6">Total</td>
                          <td class="aims-no-border aims-primary-text">&#8377;{{ total_purchase }}</td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                  <div class="aims-sub-head">
                    <div class="h4 aims-wrap-content">Consolidated</div>
                    <i class="material-icons aims-wrap-content float-right my-auto aims-trans">add</i>
                  </div>
                  <div class="float-right col-md-5">
                    <table class="table-hover table-condensed mx-auto">
                      <tbody>
                        <tr>
                          <td class="text-right aims-no-border" colspan="4">Total Payment</td>
                          <td class="aims-no-border">&#8377;{{ total_payment }}</td>
                        </tr>
                        <tr>
                          <td class="text-right aims-no-border" colspan="4">Total Purchase</td>
                          <td class="aims-no-border">&#8377;{{ total_purchase }}</td>
                        </tr>
                        <tr class="text-primary">
                          <td class="text-right aims-no-border aims-primary-text" colspan="4"> {{ balance_str }} </td>
                          <td class="aims-no-border aims-primary-text">&#8377;{{ total_balance }}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}
{% block tailscript %}
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

        if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
          if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
            $('.fixed-plugin .dropdown').addClass('open');
          }

        }

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
{% endblock %}